name: Unit Test

on:
  push:
    branches:
      - master
      - "mamoru*"
      - develop

  pull_request:
    branches:
      - master
      - "mamoru*"
      - develop

jobs:
  unit-test:

    runs-on: self-hosted

    steps:
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.21.x
    - run: go version

    - name: Setup SSH for Private Repository Access
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Checkout code
      uses: actions/checkout@v4

    - uses: actions/cache@v3
      with:
        # In order:
        # * Module download cache
        # * Build cache (Linux)
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-


    - name: Set Git to use SSH for GitHub
      run: git config --global url."git@github.com:".insteadOf "https://github.com/"

    - name: Set Git to use SSH for GitHub
      run: git config --global url."ssh://git@github.com:".insteadOf "https://github.com/"

    - name: Unit Test
      env:
        ANDROID_HOME: "" # Skip android test
      run: |
        go mod download
        make test

        




